version: '3'

services:
  app:
    build:
      context: .
    container_name: bank
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8080:8080'
  db:
    image: postgres:15.1-alpine
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - '5432:5432'