version: '3'

volumes:
  minio-data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: bank
    depends_on:
      - minio
    env_file:
      - .env-prod
    ports:
      - '8080:8080'
    networks:
      - app-network
  db:
    image: postgres:15.1-alpine
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - '5432:5432'
    networks:
      - app-network
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio

networks:
  app-network:
    driver: bridge