spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
  liquibase:
    changeLog: classpath:liquibase/db.changelog.yaml
    defaultSchema: public
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: romatempforjet@gmail.com
    password: ydkl aobk ctcc jloj
    confirmLink: http://localhost:8080/api/auth/confirm/
security:
  jwt:
    secret: ${JWT_SECRET}
    access: 2592000000
    refresh: 2592000000