spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
  liquibase:
    changeLog: classpath:liquibase/db.changelog.yaml
    defaultSchema: public
    enabled: true
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    confirmLink: ${MAIL_CONFIRMATION_LINK}
security:
  jwt:
    secret: ${JWT_SECRET}
    access: 2592000000
    refresh: 2592000000